### ISSUE TITLE
No results for basic search

### ISSUE THREAD

**Issue by luigijr44** [nestauk/clio-lite#10]
Hi there,

I have just tried to set up clio-lite and am struggling to get the basic search running.
I have one entry available in Elasticsearch but clio-lite does not return it (it returns "(0, [])").
The search works fine if I run it in Kibana:

`GET /customer/_search
{
  "query": {"bool": {"must": [{"multi_match": {"query": "john doe", "fields": []}}], "filter": []}}
}`

This is my Python code:

from clio_lite import clio_search
url = "http://localhost:9200"
index = "customer"
query = "john doe"
print(clio_search(url=url, index=index, query=query))

What am I doing wrong?
Thanks in advance.

**Comment by jaklinger** [comment]
Hi there, please accept my apologies for the late reply. I cannot reproduce your issue unfortunately as I don't have your data: however by running your example on my own local Elasticsearch I don't have any issues. 

I would note that your `kibana` query and `clio-lite` query are subtly different, and so perhaps you should try:

```python
from clio_lite import clio_search
url = "http://localhost:9200"
index = "customer"
query = {"bool": {"must": [{"multi_match": {"query": "john doe", "fields": []}}], "filter": []}} 
print(clio_search(url=url, index=index, query=query))
```

**Comment by jaklinger** [comment]
please do not hesitate to re-open if the issue is not resolved.

If you do so, you could kindly also specify:

* Elasticsearch version
* python version
* Operating system

All the best
