### ISSUE TITLE
Installation Assistance

### ISSUE THREAD

**Issue by weisisheng** [nestauk/clio-lite#9]
I must be missing something fundamental. Using a virtual env  with python 2.7 on ubuntu 20.04...

I am trying to use clio-lite to connect searchkit with an existing ES instance protected with IAM policies only. The deploy.sh script looks for multiple config files in the /config folder but only one exists (range_upper_limit).  I tried adding blank files and also individual files with the es domain hyperlink (https://foo) and a toy function name.  Also file contents in quotations.  Errors return that the 1. the files need an item (aws: error: argument --function-name: expected one argument) or 2. they are not in the right format.  Should these be in json format {"function_name":"foo_function"} and {"allowed_endpoints":"foo_endpoint"}?

Thanks in advance.

**Comment by jaklinger** [comment]
Hi there, please accept my apologies for the late reply, and thank you for specifying your systems specs. (Firstly I would say that I haven't tested clio-lite with python 2.7 so I can't guarantee behaviour. In fact, I would naively expect it to fail).

Thanks for highlighting this shortcoming of my documentation! You need to specify these endpoint URLs in a file, as specified in my updated documentation

https://github.com/nestauk/clio-lite/tree/master/config

If this doesn't help then please don't hesitate to reopen the issue, and I will be better at replying next time!

**Comment by weisisheng** [comment]
Thanks very much for your kind follow-up.  I will return to this great project and give it another try next week.  All the best.
